#!/bin/sh

set -e


if ! getent group raspotify >/dev/null 2>&1; then
    addgroup --system raspotify
fi

if ! id raspotify >/dev/null 2>&1; then
    adduser --system --disabled-password --disabled-login \
        --home /var/cache/raspotify --ingroup raspotify raspotify
fi

mkdir -m 0755 -p /opt/raspotify
chown -R raspotify:raspotify /opt/raspotify

if test -f "/opt/raspotify/conf.usercustom"; then
    mv /opt/raspotify/conf.properties /opt/raspotify/conf.example
    mv /opt/raspotify/conf.usercustom /opt/raspotify/conf.properties
fi

adduser raspotify audio

# Based off what debhelper would have added

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask raspotify.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled raspotify.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable raspotify.service >/dev/null || true
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state raspotify.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
    deb-systemd-invoke start raspotify.service >/dev/null || true
fi
