#!/bin/sh

set -e


if ! getent group raspotify >/dev/null 2>&1; then
    addgroup --system raspotify
fi

if ! id raspotify >/dev/null 2>&1; then
    adduser --system --disabled-password --disabled-login \
        --home /var/cache/raspotify --ingroup raspotify raspotify
fi

mkdir -m 0755 -p /var/cache/raspotify
chown raspotify:raspotify /var/cache/raspotify
adduser raspotify audio

# Make sure `--linear-volume' is properly renamed
if [ -f /etc/default/raspotify ]; then
    sed -i 's/--linear-volume/--volume-ctrl linear/' /etc/default/raspotify
fi

if [ -f /etc/systemd/system/raspotify.service ]; then
    sed -i 's/--linear-volume/--volume-ctrl linear/' /etc/systemd/system/raspotify.service
fi

# Rename deprecated option names
if [ -f /etc/default/raspotify ]; then
    sed -i 's/--mixer-card/--alsa-mixer-device/' /etc/default/raspotify
fi

if [ -f /etc/systemd/system/raspotify.service ]; then
    sed -i 's/--mixer-card/--alsa-mixer-device/' /etc/systemd/system/raspotify.service
fi

if [ -f /etc/default/raspotify ]; then
    sed -i 's/--mixer-index/--alsa-mixer-index/' /etc/default/raspotify
fi

if [ -f /etc/systemd/system/raspotify.service ]; then
    sed -i 's/--mixer-index/--alsa-mixer-index/' /etc/systemd/system/raspotify.service
fi

if [ -f /etc/default/raspotify ]; then
    sed -i 's/--mixer-name/--alsa-mixer-name/' /etc/default/raspotify
fi

if [ -f /etc/systemd/system/raspotify.service ]; then
    sed -i 's/--mixer-name/--alsa-mixer-name/' /etc/systemd/system/raspotify.service
fi


# Based off what debhelper would have added

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask raspotify.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled raspotify.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable raspotify.service >/dev/null || true
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state raspotify.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
    deb-systemd-invoke start raspotify.service >/dev/null || true
fi
