#!/bin/sh

# Based off what debhelper would have added

set -e

if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask raspotify.service >/dev/null
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge raspotify.service >/dev/null
        deb-systemd-helper unmask raspotify.service >/dev/null
        deb-systemd-helper purge raspotify-crash-report-generator.service >/dev/null
        deb-systemd-helper unmask raspotify-crash-report-generator.service >/dev/null
    fi
    # Delete any config files
    rm -rf /etc/raspotify
    # Delete any cache files created by systemd
    rm -rf /var/cache/private/raspotify
    rm -rf /var/lib/private/raspotify
    # Delete any cache files created the old fashioned way
    rm -rf /var/cache/raspotify
    rm -rf /var/lib/raspotify
    # Delete the service files
    rm -rf /etc/systemd/system/raspotify.service
    rm -rf /etc/systemd/system/raspotify-crash-report-generator.service
    # Delete any drop-in overrides.
    rm -rf /etc/systemd/system/raspotify.service.d
    rm -rf /etc/systemd/system/raspotify-crash-report-generator.service.d
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
