#!/bin/sh

# Fix changes in command line arguments for librespot v0.1.3

if [ -f /etc/default/raspotify ]; then
    sed -i 's/--linear-volume/--volume-ctrl=linear/' /etc/default/raspotify > /dev/null 2>&1
fi

if [ -f /etc/systemd/system/raspotify.service ]; then
    sed -i 's/--linear-volume/--volume-ctrl=linear/' /etc/systemd/system/raspotify.service > /dev/null 2>&1
fi