#!/bin/sh

# Fix changes in command line arguments for librespot v0.1.3

if [ -e /etc/default/raspotify ]; then
    sed -i 's/--linear-volume/--volume-ctrl=linear/' /etc/default/raspotify >/dev/null 2>&1
fi
