# vi: se et ts=2 sts=2 sw=2:

name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of release with .deb file assets attached. Omit this field to deploy the latest release.'
        required: false

permissions:
  contents: read        # scope to the minimum your job needs

jobs:
  apt_deploy:
    runs-on: ubuntu-latest
    name: Deploy Release
    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_SECRET_KEY_BASE64: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
      RELEASE_TAG: ${{ github.event.inputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Checkout gh-pages branch
        uses: actions/checkout@v7
        with:
          ref: gh-pages
          path: apt-repo

      - name: Download .deb files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ github.event.inputs.tag }} --pattern "*.deb"

      - name: Install reprepro
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro

      - name: Create and deploy repo
        run: ./deploy-apt-repo.sh
