# vi: se et ts=2 sts=2 sw=2:

name: Deploy Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apt_deploy:
    runs-on: ubuntu-latest
    name: Deploy Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Checkout gh-pages branch
        uses: actions/checkout@v7
        with:
          ref: gh-pages
          path: apt-repo

      - name: Determine release tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release view --json tagName --jq '.tagName')
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Download .deb files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download --pattern "*.deb"

      - name: Install reprepro
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro

      - name: Create and deploy repo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_SECRET_KEY_BASE64: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
        run: ./deploy-apt-repo.sh
